os: osx

sudo: true

language: node_js

node_js:
  - node

addons:
  ssh_known_hosts: $PRODUCTION_SERVER
  apt:
    packages:
      - expect

notifications:
  email:
    recipients:
      - sylvia.ji@nyu.edu
      - jl8456@nyu.edu
      - cem663@nyu.edu
    on_success: never
    on_failure: always

before_script:
  - cd back-end
  - npm install

script:
  - npm test

after_script:
  - cd ..

# continuous integration
deploy:
  - provider: script

    script:
      - chmod +x deploy.expect
      - expect deploy.expect

    # only deploy master branch content
    on:
      branch: master
